DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING NOT NULL,
	DESCRIPTION CHARACTER VARYING,
	RELEASE_DATE DATE,
	DURATION INTEGER,
	MPA_ID CHARACTER VARYING,
	CONSTRAINT FILMS_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_FILM_ID ON PUBLIC.FILMS (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	USERNAME CHARACTER VARYING,
	LOGIN CHARACTER VARYING NOT NULL,
	EMAIL VARCHAR_IGNORECASE(256) NOT NULL,
	BIRTHDAY DATE,
	CONSTRAINT USERS_PK PRIMARY KEY (ID),
	CONSTRAINT USERS_UN UNIQUE (LOGIN)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_USER_ID ON PUBLIC.USERS (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	REQUESTER_ID INTEGER NOT NULL,
	ACCEPTER_ID INTEGER NOT NULL,
	CONSTRAINT FRIENDS_PK PRIMARY KEY (ID),
	CONSTRAINT FRIENDS_FK FOREIGN KEY (REQUESTER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FRIENDS_FK_1 FOREIGN KEY (ACCEPTER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PUBLIC.LIKES (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	USER_ID INTEGER NOT NULL,
	FILM_ID INTEGER NOT NULL,
	CONSTRAINT LIKES_PK PRIMARY KEY (ID),
	CONSTRAINT LIKES_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT LIKES_FK_1 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRE (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	GENRE_NAME CHARACTER VARYING NOT NULL,
	CONSTRAINT GENRE_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMGENRE (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FILM_ID INTEGER NOT NULL,
	GENRE_ID INTEGER NOT NULL,
	CONSTRAINT FILMGENRE_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FILMGENRE_FK_1 FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PUBLIC.MPA (
	ID INTEGER NOT NULL,
	NAME CHARACTER VARYING,
	CONSTRAINT MPA_PK PRIMARY KEY (ID)
);

INSERT INTO MPA VALUES (1, 'G');
INSERT INTO MPA VALUES (2, 'PG');
INSERT INTO MPA VALUES (3, 'PG-13');
INSERT INTO MPA VALUES (4, 'R');
INSERT INTO MPA VALUES (5, 'NC-17');

INSERT INTO GENRE VALUES (1, 'Комедия');
INSERT INTO GENRE VALUES (2, 'Драма');
INSERT INTO GENRE VALUES (3, 'Мультфильм');
INSERT INTO GENRE VALUES (4, 'Триллер');
INSERT INTO GENRE VALUES (5, 'Документальный');
INSERT INTO GENRE VALUES (6, 'Боевик');